x-common: &common-setup
  image: fabook/mik:v0.0.5
  network_mode: host
  privileged: true
  volumes:
    - ${HOME}/.Xauthority:/home/mobile/.Xauthority:rw
    - .:/home/ros2_ws/src:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev/dri:/dev/dri:rw

  environment:
    - "DISPLAY"
    - "QT_X11_NO_MITSHM=1"
  ports:
    - "9090:9090"
  entrypoint: >
    bash -c "
    source /opt/ros/humble/setup.bash && /bin/bash
    "

services:
  terminal:
    <<: *common-setup
    stdin_open: true  # dsocker run -i
    tty: true        # docker run -t
    working_dir: /home/ros2_ws
    command: []
