# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - drone_controller

  drone_controller:
    type: FollowJointTrajectory
    joints:
      [prop1_joint]
    action_ns: follow_joint_trajectory
    default: true
